### ISSUE TITLE
JS interface into anypiajs

### ISSUE THREAD

**Issue by AlexMerritt** [codeforboston/anypia-js#11]
Create an interface into the c++ anypiajs interface.

- These functions from this interface will mirror anything that we expose from anypiajs.
- Create a html template so that when we build the emscription we use our own html page rather than what is auto generated.
- The interface should look something like https://github.com/azavea/loam/blob/develop/src/worker.js
- The interface should be easily called to make the front end as easy as possible
- We also need to determine how we want to be passing data into and out of the interface.

**Comment by thadk** [comment]
Closed by #13 and https://github.com/codeforboston/windfall-elimination/pull/196

It works! Many thanks @mrpippy.
![image](https://user-images.githubusercontent.com/283343/92298259-dfb84000-ef14-11ea-942c-d62b4ad8bb9e.png)
https://deploy-preview-196--windfall-develop.netlify.app

Open issue of using in NodeJS here: https://github.com/codeforboston/windfall-elimination/issues/209
