### ISSUE TITLE
Add a license.md

### ISSUE THREAD

**Issue by thadk** [codeforboston/anypia-js#15]
Hi @mrpippy, Thanks again for all the help getting this project rolling. Do you have any objection to [re-licensing this CC0](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) along the [lines of these GSA 18F guidelines](https://github.com/18F/open-source-policy/issues/95#issuecomment-610417580) so this could be adopted more broadly inside/outside gov if desired? I don't know much about the patent issues but happy to consider broader licenses too.

I think we and @AlexMerritt are the only contributors so far but there were some more interested folks tonight at hacknight. The code is running great in a React environment over at https://github.com/codeforboston/windfall-elimination/ .

**Comment by mrpippy** [comment]
Hey @thadk, no objection from me to re-licensing under CC0.
